### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by HHJUPUP** [GAIR-Lab/IISAN#1]
尊敬的作者您好！我对您的IISAN项目非常感兴趣，但在运行过程中发现缺少pinterest等数据集，这些数据如何获取呢？谢谢！

**Comment by junchen-fu** [comment]
感谢您的关注！

我们的IISAN架构基于多模态内容设计，所以它仅适用于包含原始多模态信息（如文本和图像）的数据集。目前已知适用于IISAN的推荐系统数据集主要包括以下几个：

- **亚马逊数据集**：例如本文中我们自行收集并提供的数据。
- **H&M数据集**：[H&M Personalized Fashion Recommendations](https://www.kaggle.com/competitions/h-and-m-personalized-fashion-recommendations)。
- **Microlens数据集**：[Microlens](https://github.com/westlake-repl/MicroLens)。
- **Ninerec数据集**：[Ninerec](https://github.com/westlake-repl/NineRec)。

如果其他数据集不包含文本或图像信息，则无法适配IISAN架构。例如，对于Pinterest数据集，我不太熟悉这个数据集，如果能够收集到其中的文本和图片信息，按照本文中的数据处理代码进行处理，便可以适配IISAN架构；但如果数据仅包含ID或单模态信息，则无法使用IISAN架构。不知道这样说能否回答您的问题呢？

**Comment by HHJUPUP** [comment]
非常感谢您的详细解释，这让我对IISAN架构的适配数据集有了更清晰的理解。我会进一步研究如何收集和整合数据集中的文本和图片信息，以便按照IISAN架构的数据预处理流程进行适配。再次感谢您的耐心解答！

**Comment by HHJUPUP** [comment]
非常感谢您的详细解释，这让我对IISAN架构的适配数据集有了更清晰的理解。我会进一步研究如何收集和整合数据集中的文本和图片信息，以便按照IISAN架构的数据预处理流程进行适配。再次感谢您的耐心解答！
